# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'setScheduleTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for setScheduleTest
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'setScheduleTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'setScheduleTestUITests' do
    # Pods for testing
  end

end
